# site settings
email: robert.davies@stats.ox.ac.uk
description: Statistical and Population Genomics, Department of Statistics, University of Oxford
## title: Davies lab
## subtitle: University of Oxford, Department of Statistics
baseurl:
url: https://davieslab.github.io

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10 # can change this

# social settings
github_url: https://github.com/rwdavies/
twitter_url: https://twitter.com/robbie_stats

# build settings
markdown: kramdown

sass:
  style: compressed
